spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
#debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

